### ISSUE TITLE
Help with running the project

### ISSUE THREAD

**Issue by Manjul1225** [nickpadd/EuropeanFootballLeaguePredictor#60]
Hi.
I am manul, a web & AI developer.
I am interested in Football match predict.
And i suprise to your EuropeanFootballleaguePredictor.
I study your code and  have some problems.
Please help me.
First, Please explain how to use this code.
Second, I want to know AI future.
Thanks.
My github - Manjul1225

**Comment by Manjul1225** [comment]
My communication tool;
discord- codestar007
skype - codestar007
telegram - @goldenbutter1234
Gmail - manjulbhargava660@gmail.com

**Comment by nickpadd** [comment]
Closed as there is no follow up
