### ISSUE TITLE
Upcoming Matches not updating when not scraping the bookmaker

### ISSUE THREAD

**Issue by nickpadd** [nickpadd/EuropeanFootballLeaguePredictor#81]
This is a new issue posted by @awarenessaspie in https://github.com/nickpadd/EuropeanFootballLeaguePredictor/issues/80#issuecomment-2394386910_

**Comment by nickpadd** [comment]
[@awarenessaspie ](https://github.com/awarenessaspie) i cannot reproduce your results. For me, if not scraping from the bookmaker, it produces predictions for the upcoming 15 days of matches. Please provide the logs of running your update script in order to debug.

**Comment by ProcuratorTitan** [comment]
now I can confirm that it works great job

**Comment by awarenessaspie** [comment]
I think it's vpn related because football-data.co.uk is not accessible in my country and I get the following error;
2024-10-07 17:37:40.257 | ERROR | __main__:main:67 - Failed to download data for season 2017. Response code: 404.

**Comment by nickpadd** [comment]
@awarenessaspie I am afraid that is an issue that I cannot support to deal with. But I think finding a free vpn that let's you access the data-co-uk domain should easily solve the issue!
